news:
  db:
    url: jdbc:h2:mem:newsDB
    username: sa
    password:
  google:
    client-id: 1063003635047-nfd4frr7i3jonjk7reevti6drhfgmk1b.apps.googleusercontent.com
    client-secret: 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
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto:none
  h2:
    console:
      enabled: true
  liquibase:
    contexts: local

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

springdoc:
  show-login-endpoint: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${HOSTNAME}"